version: '3'

services:
  app:
    image: 'dockerappimage'
    build:
      context: .
    container_name: app
    ports:
      - '8080:8080'
    environment:
      - BOOK_STORE_DB_HOST=localhost
      - BOOK_STORE_DB_PORT=5432
      - BOOK_STORE_DB_NAME=book_store
      - BOOK_STORE_DB_SCHEMA=public
      - BOOK_STORE_DB_USERNAME=postgres
      - BOOK_STORE_DB_PASSWORD=testdoc
      - BOOK_STORE_MAIL_USERNAME=smdon43@gmail.com
      - BOOK_STORE_MAIL_PASSWORD=qweasdhdgwrk
      - BOOK_STORE_JWT_SECRET_KEY=test