spring:
  datasource:
    url: jdbc:postgresql://${BOOK_STORE_DB_HOST}:${BOOK_STORE_DB_PORT}/${BOOK_STORE_DB_NAME}?currentSchema=${BOOK_STORE_DB_SCHEMA}
    username: ${BOOK_STORE_DB_USERNAME}
    password: ${BOOK_STORE_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_schema: ${BOOK_STORE_DB_SCHEMA}
    hibernate:
      ddl-auto: none
    open-in-view:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: ${BOOK_STORE_DB_SCHEMA}
    liquibase-schema: ${BOOK_STORE_DB_SCHEMA}
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: smdovn42@gmail.com
    password: lgrvgizrhsoauhbl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
security:
  auth:
    whitelist: >
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,  
      /configuration/security,
      /swagger-ui.html,
      /webjars/**,
      /api/public/**,
      /v3/api-docs/**,
      /v3/api-docs,
      /swagger-ui/**,
      /v2/api-docs,
      /api/v1/public/**,
      /ws-registration/**,
      api/v1/public/accounts/**

  jwt:
    secret-key: ${BOOK_STORE_JWT_SECRET_KEY}
